# Generated by Django 4.1 on 2022-09-28 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppGame', '0003_comentarios_alter_consola_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consola',
            options={},
        ),
        migrations.AlterModelOptions(
            name='juegos',
            options={},
        ),
        migrations.AlterModelOptions(
            name='jugador',
            options={},
        ),
        migrations.AlterModelManagers(
            name='consola',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='juegos',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='jugador',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='consola',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='consola',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='juegos',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='juegos',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='jugador',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='jugador',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='jugador',
            name='slug',
        ),
        migrations.AlterField(
            model_name='consola',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='consola',
            name='contenido',
            field=models.TextField(null=True, verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='consola',
            name='imagen',
            field=models.ImageField(null=True, upload_to='jugador', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='consola',
            name='publicado',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='consola',
            name='subtitulo',
            field=models.CharField(max_length=50, null=True, verbose_name='Subtitulo'),
        ),
        migrations.AlterField(
            model_name='consola',
            name='titulo',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='juegos',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='juegos',
            name='contenido',
            field=models.TextField(null=True, verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='juegos',
            name='imagen',
            field=models.ImageField(null=True, upload_to='jugador', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='juegos',
            name='publicado',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='juegos',
            name='subtitulo',
            field=models.CharField(max_length=50, null=True, verbose_name='Subtitulo'),
        ),
        migrations.AlterField(
            model_name='juegos',
            name='titulo',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='apellido',
            field=models.CharField(max_length=50, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='apodo',
            field=models.CharField(max_length=30, verbose_name='apodo'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='contenido',
            field=models.TextField(null=True, verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='imagen',
            field=models.ImageField(null=True, upload_to='jugador', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='publicado',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='subtitulo',
            field=models.CharField(max_length=50, null=True, verbose_name='Subtitulo'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='titulo',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Titulo'),
        ),
    ]
