# Generated by Django 4.1 on 2022-09-28 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppGame', '0004_alter_consola_options_alter_juegos_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jugador',
            old_name='contenido',
            new_name='contenido_post',
        ),
        migrations.RenameField(
            model_name='jugador',
            old_name='imagen',
            new_name='imagen_post',
        ),
        migrations.RenameField(
            model_name='jugador',
            old_name='subtitulo',
            new_name='subtitulo_post',
        ),
        migrations.RenameField(
            model_name='jugador',
            old_name='titulo',
            new_name='titulo_post',
        ),
    ]
