# Generated by Django 4.1 on 2022-09-28 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppGame', '0006_rename_contenido_juegos_contenido_juego_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consola',
            old_name='author',
            new_name='autor',
        ),
        migrations.RenameField(
            model_name='juegos',
            old_name='author',
            new_name='autor',
        ),
        migrations.RenameField(
            model_name='jugador',
            old_name='author',
            new_name='autor',
        ),
    ]
