# Generated by Django 4.1 on 2022-09-28 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGame', '0007_rename_author_consola_autor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juegos',
            name='imagen_juego',
            field=models.ImageField(null=True, upload_to='Media/jugador', verbose_name='Imagen'),
        ),
    ]
