# Generated by Django 4.1 on 2022-09-29 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGame', '0008_alter_juegos_imagen_juego'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juegos',
            name='imagen_juego',
            field=models.ImageField(null=True, upload_to='media/jugador', verbose_name='Imagen'),
        ),
    ]
