# Generated by Django 4.1 on 2022-09-29 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGame', '0009_alter_juegos_imagen_juego'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juegos',
            name='fecha_salida',
            field=models.DateField(blank=True),
        ),
    ]
