# Generated by Django 4.1 on 2022-09-29 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppGame', '0010_alter_juegos_fecha_salida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='juegos',
            name='fecha_salida',
        ),
    ]
