# Generated by Django 4.1 on 2022-09-29 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGame', '0011_remove_juegos_fecha_salida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consola',
            name='imagen',
            field=models.ImageField(null=True, upload_to='media/consola', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='juegos',
            name='imagen_juego',
            field=models.ImageField(null=True, upload_to='media/juegos', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='imagen_post',
            field=models.ImageField(null=True, upload_to='media/jugador', verbose_name='Imagen'),
        ),
    ]
