# Generated by Django 4.1 on 2022-09-29 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGame', '0012_alter_consola_imagen_alter_juegos_imagen_juego_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='imagen_post',
            field=models.ImageField(null=True, upload_to='jugador', verbose_name='Imagen'),
        ),
    ]
