# Generated by Django 4.1 on 2022-09-29 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGame', '0013_alter_jugador_imagen_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consola',
            name='imagen',
            field=models.ImageField(null=True, upload_to='consola/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='juegos',
            name='imagen_juego',
            field=models.ImageField(null=True, upload_to='juegos/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='imagen_post',
            field=models.ImageField(null=True, upload_to='jugador/', verbose_name='Imagen'),
        ),
    ]
