# Generated by Django 4.1 on 2022-09-29 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGame', '0014_alter_consola_imagen_alter_juegos_imagen_juego_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consola',
            name='imagen',
            field=models.ImageField(null=True, upload_to='consola', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='juegos',
            name='imagen_juego',
            field=models.ImageField(null=True, upload_to='juegos', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='imagen_post',
            field=models.ImageField(null=True, upload_to='jugador', verbose_name='Imagen'),
        ),
    ]
