# Generated by Django 4.1 on 2022-10-02 20:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppGame', '0021_rename_imagen_consola_imagen_consola'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consola',
            name='contenido',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Contenido'),
        ),
    ]
