# Generated by Django 4.1 on 2022-10-02 20:51

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppGame', '0022_alter_consola_contenido'),
    ]

    operations = [
        migrations.AddField(
            model_name='consola',
            name='media_consola',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consola',
            name='contenido',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Contenido'),
        ),
    ]
